// Generated by gencpp from file ssafyrari/Velo.msg
// DO NOT EDIT!


#ifndef SSAFYRARI_MESSAGE_VELO_H
#define SSAFYRARI_MESSAGE_VELO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ssafyrari
{
template <class ContainerAllocator>
struct Velo_
{
  typedef Velo_<ContainerAllocator> Type;

  Velo_()
    : velo()  {
    }
  Velo_(const ContainerAllocator& _alloc)
    : velo(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _velo_type;
  _velo_type velo;





  typedef boost::shared_ptr< ::ssafyrari::Velo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ssafyrari::Velo_<ContainerAllocator> const> ConstPtr;

}; // struct Velo_

typedef ::ssafyrari::Velo_<std::allocator<void> > Velo;

typedef boost::shared_ptr< ::ssafyrari::Velo > VeloPtr;
typedef boost::shared_ptr< ::ssafyrari::Velo const> VeloConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ssafyrari::Velo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ssafyrari::Velo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ssafyrari::Velo_<ContainerAllocator1> & lhs, const ::ssafyrari::Velo_<ContainerAllocator2> & rhs)
{
  return lhs.velo == rhs.velo;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ssafyrari::Velo_<ContainerAllocator1> & lhs, const ::ssafyrari::Velo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ssafyrari

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ssafyrari::Velo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ssafyrari::Velo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ssafyrari::Velo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ssafyrari::Velo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ssafyrari::Velo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ssafyrari::Velo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ssafyrari::Velo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bed164f0ee5d61bd8bc4c275368453b2";
  }

  static const char* value(const ::ssafyrari::Velo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbed164f0ee5d61bdULL;
  static const uint64_t static_value2 = 0x8bc4c275368453b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::ssafyrari::Velo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ssafyrari/Velo";
  }

  static const char* value(const ::ssafyrari::Velo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ssafyrari::Velo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] velo\n"
;
  }

  static const char* value(const ::ssafyrari::Velo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ssafyrari::Velo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.velo);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Velo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ssafyrari::Velo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ssafyrari::Velo_<ContainerAllocator>& v)
  {
    s << indent << "velo[]" << std::endl;
    for (size_t i = 0; i < v.velo.size(); ++i)
    {
      s << indent << "  velo[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.velo[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SSAFYRARI_MESSAGE_VELO_H
