// Generated by gencpp from file ssafyrari/global_data.msg
// DO NOT EDIT!


#ifndef SSAFYRARI_MESSAGE_GLOBAL_DATA_H
#define SSAFYRARI_MESSAGE_GLOBAL_DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ssafyrari
{
template <class ContainerAllocator>
struct global_data_
{
  typedef global_data_<ContainerAllocator> Type;

  global_data_()
    : nodes_idx()
    , links_idx()
    , nodes_idx1()
    , links_idx1()
    , nodes_idx2()
    , links_idx2()
    , change(0)
    , CC()
    , DD()  {
    }
  global_data_(const ContainerAllocator& _alloc)
    : nodes_idx(_alloc)
    , links_idx(_alloc)
    , nodes_idx1(_alloc)
    , links_idx1(_alloc)
    , nodes_idx2(_alloc)
    , links_idx2(_alloc)
    , change(0)
    , CC(_alloc)
    , DD(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _nodes_idx_type;
  _nodes_idx_type nodes_idx;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _links_idx_type;
  _links_idx_type links_idx;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _nodes_idx1_type;
  _nodes_idx1_type nodes_idx1;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _links_idx1_type;
  _links_idx1_type links_idx1;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _nodes_idx2_type;
  _nodes_idx2_type nodes_idx2;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _links_idx2_type;
  _links_idx2_type links_idx2;

   typedef uint32_t _change_type;
  _change_type change;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _CC_type;
  _CC_type CC;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _DD_type;
  _DD_type DD;





  typedef boost::shared_ptr< ::ssafyrari::global_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ssafyrari::global_data_<ContainerAllocator> const> ConstPtr;

}; // struct global_data_

typedef ::ssafyrari::global_data_<std::allocator<void> > global_data;

typedef boost::shared_ptr< ::ssafyrari::global_data > global_dataPtr;
typedef boost::shared_ptr< ::ssafyrari::global_data const> global_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ssafyrari::global_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ssafyrari::global_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ssafyrari::global_data_<ContainerAllocator1> & lhs, const ::ssafyrari::global_data_<ContainerAllocator2> & rhs)
{
  return lhs.nodes_idx == rhs.nodes_idx &&
    lhs.links_idx == rhs.links_idx &&
    lhs.nodes_idx1 == rhs.nodes_idx1 &&
    lhs.links_idx1 == rhs.links_idx1 &&
    lhs.nodes_idx2 == rhs.nodes_idx2 &&
    lhs.links_idx2 == rhs.links_idx2 &&
    lhs.change == rhs.change &&
    lhs.CC == rhs.CC &&
    lhs.DD == rhs.DD;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ssafyrari::global_data_<ContainerAllocator1> & lhs, const ::ssafyrari::global_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ssafyrari

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ssafyrari::global_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ssafyrari::global_data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ssafyrari::global_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ssafyrari::global_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ssafyrari::global_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ssafyrari::global_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ssafyrari::global_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "835f29fffac894f6ad460b7c08855f8c";
  }

  static const char* value(const ::ssafyrari::global_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x835f29fffac894f6ULL;
  static const uint64_t static_value2 = 0xad460b7c08855f8cULL;
};

template<class ContainerAllocator>
struct DataType< ::ssafyrari::global_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ssafyrari/global_data";
  }

  static const char* value(const ::ssafyrari::global_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ssafyrari::global_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] nodes_idx\n"
"string[] links_idx\n"
"string[] nodes_idx1\n"
"string[] links_idx1\n"
"string[] nodes_idx2\n"
"string[] links_idx2\n"
"uint32 change\n"
"float64[] CC\n"
"float64[] DD\n"
;
  }

  static const char* value(const ::ssafyrari::global_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ssafyrari::global_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nodes_idx);
      stream.next(m.links_idx);
      stream.next(m.nodes_idx1);
      stream.next(m.links_idx1);
      stream.next(m.nodes_idx2);
      stream.next(m.links_idx2);
      stream.next(m.change);
      stream.next(m.CC);
      stream.next(m.DD);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct global_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ssafyrari::global_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ssafyrari::global_data_<ContainerAllocator>& v)
  {
    s << indent << "nodes_idx[]" << std::endl;
    for (size_t i = 0; i < v.nodes_idx.size(); ++i)
    {
      s << indent << "  nodes_idx[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.nodes_idx[i]);
    }
    s << indent << "links_idx[]" << std::endl;
    for (size_t i = 0; i < v.links_idx.size(); ++i)
    {
      s << indent << "  links_idx[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.links_idx[i]);
    }
    s << indent << "nodes_idx1[]" << std::endl;
    for (size_t i = 0; i < v.nodes_idx1.size(); ++i)
    {
      s << indent << "  nodes_idx1[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.nodes_idx1[i]);
    }
    s << indent << "links_idx1[]" << std::endl;
    for (size_t i = 0; i < v.links_idx1.size(); ++i)
    {
      s << indent << "  links_idx1[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.links_idx1[i]);
    }
    s << indent << "nodes_idx2[]" << std::endl;
    for (size_t i = 0; i < v.nodes_idx2.size(); ++i)
    {
      s << indent << "  nodes_idx2[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.nodes_idx2[i]);
    }
    s << indent << "links_idx2[]" << std::endl;
    for (size_t i = 0; i < v.links_idx2.size(); ++i)
    {
      s << indent << "  links_idx2[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.links_idx2[i]);
    }
    s << indent << "change: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.change);
    s << indent << "CC[]" << std::endl;
    for (size_t i = 0; i < v.CC.size(); ++i)
    {
      s << indent << "  CC[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.CC[i]);
    }
    s << indent << "DD[]" << std::endl;
    for (size_t i = 0; i < v.DD.size(); ++i)
    {
      s << indent << "  DD[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.DD[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SSAFYRARI_MESSAGE_GLOBAL_DATA_H
