// Generated by gencpp from file ssafy_3/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SSAFY_3_MESSAGE_ADDTWOINTS_H
#define SSAFY_3_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <ssafy_3/AddTwoIntsRequest.h>
#include <ssafy_3/AddTwoIntsResponse.h>


namespace ssafy_3
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace ssafy_3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ssafy_3::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::ssafy_3::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::ssafy_3::AddTwoInts > {
  static const char* value()
  {
    return "ssafy_3/AddTwoInts";
  }

  static const char* value(const ::ssafy_3::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::ssafy_3::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::ssafy_3::AddTwoInts >
template<>
struct MD5Sum< ::ssafy_3::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ssafy_3::AddTwoInts >::value();
  }
  static const char* value(const ::ssafy_3::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ssafy_3::AddTwoIntsRequest> should match
// service_traits::DataType< ::ssafy_3::AddTwoInts >
template<>
struct DataType< ::ssafy_3::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::ssafy_3::AddTwoInts >::value();
  }
  static const char* value(const ::ssafy_3::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ssafy_3::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::ssafy_3::AddTwoInts >
template<>
struct MD5Sum< ::ssafy_3::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ssafy_3::AddTwoInts >::value();
  }
  static const char* value(const ::ssafy_3::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ssafy_3::AddTwoIntsResponse> should match
// service_traits::DataType< ::ssafy_3::AddTwoInts >
template<>
struct DataType< ::ssafy_3::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::ssafy_3::AddTwoInts >::value();
  }
  static const char* value(const ::ssafy_3::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SSAFY_3_MESSAGE_ADDTWOINTS_H
