// Generated by gencpp from file ssafy_3/GPS.msg
// DO NOT EDIT!


#ifndef SSAFY_3_MESSAGE_GPS_H
#define SSAFY_3_MESSAGE_GPS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ssafy_3
{
template <class ContainerAllocator>
struct GPS_
{
  typedef GPS_<ContainerAllocator> Type;

  GPS_()
    : longitude(0.0)
    , latitude(0.0)
    , eastOffset(0.0)
    , northOffset(0.0)  {
    }
  GPS_(const ContainerAllocator& _alloc)
    : longitude(0.0)
    , latitude(0.0)
    , eastOffset(0.0)
    , northOffset(0.0)  {
  (void)_alloc;
    }



   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _eastOffset_type;
  _eastOffset_type eastOffset;

   typedef double _northOffset_type;
  _northOffset_type northOffset;





  typedef boost::shared_ptr< ::ssafy_3::GPS_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ssafy_3::GPS_<ContainerAllocator> const> ConstPtr;

}; // struct GPS_

typedef ::ssafy_3::GPS_<std::allocator<void> > GPS;

typedef boost::shared_ptr< ::ssafy_3::GPS > GPSPtr;
typedef boost::shared_ptr< ::ssafy_3::GPS const> GPSConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ssafy_3::GPS_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ssafy_3::GPS_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ssafy_3::GPS_<ContainerAllocator1> & lhs, const ::ssafy_3::GPS_<ContainerAllocator2> & rhs)
{
  return lhs.longitude == rhs.longitude &&
    lhs.latitude == rhs.latitude &&
    lhs.eastOffset == rhs.eastOffset &&
    lhs.northOffset == rhs.northOffset;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ssafy_3::GPS_<ContainerAllocator1> & lhs, const ::ssafy_3::GPS_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ssafy_3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ssafy_3::GPS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ssafy_3::GPS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ssafy_3::GPS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ssafy_3::GPS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ssafy_3::GPS_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ssafy_3::GPS_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ssafy_3::GPS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "873a81f2a8fa219c502e38ff7956f609";
  }

  static const char* value(const ::ssafy_3::GPS_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x873a81f2a8fa219cULL;
  static const uint64_t static_value2 = 0x502e38ff7956f609ULL;
};

template<class ContainerAllocator>
struct DataType< ::ssafy_3::GPS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ssafy_3/GPS";
  }

  static const char* value(const ::ssafy_3::GPS_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ssafy_3::GPS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 longitude\n"
"float64 latitude\n"
"float64 eastOffset\n"
"float64 northOffset\n"
"\n"
;
  }

  static const char* value(const ::ssafy_3::GPS_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ssafy_3::GPS_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.longitude);
      stream.next(m.latitude);
      stream.next(m.eastOffset);
      stream.next(m.northOffset);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GPS_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ssafy_3::GPS_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ssafy_3::GPS_<ContainerAllocator>& v)
  {
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "eastOffset: ";
    Printer<double>::stream(s, indent + "  ", v.eastOffset);
    s << indent << "northOffset: ";
    Printer<double>::stream(s, indent + "  ", v.northOffset);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SSAFY_3_MESSAGE_GPS_H
